version: 2.1
orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run heroku-prebuild
          name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true

workflows:
  build_my_app:
    jobs:
      - build
      - deploy:
          requires:
            - build 
          filters:
            branches:
              only: master